# Generated by Django 4.1.7 on 2023-03-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('time', models.TimeField()),
                ('count', models.IntegerField()),
                ('notes', models.TextField(max_length=255)),
            ],
        ),
    ]
